---
- name: Create AD Users from CSV
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Read CSV file
      read_csv:
        path: gegevens.csv
      register: csv_content

    - name: Use CSV Data as Variables
      set_fact:
        users_data: "{{ csv_content.list }}"

- name: Create AD Users from CSV
  hosts: winservers
  gather_facts: yes
  tasks:
    - name: Create AD Users
      win_domain_user:
        name: "{{ item.Gebruikersnaam }}"
        firstname: "{{ item.Voornaam }}"
        surname: "{{ item.Achternaam }}"
        password: "Welkom123456"  # Set a secure password
        street_address: "{{ item.Adres }}"
        postal_code: "{{ item.Postcode }}"
        city: "{{ item.Plaatsnaam }}"
        state: present
        email: '"{{ item.Gebruikersnaam }}"@{{ domainname }}'
        attributes: "{{ item.attributes|default(omit) }}"
        domain_admin_user: "{{ domainuser }}"
        domain_admin_password: "{{ domainpass }}"
      with_items: "{{ users_data }}"