---
- name: Create AD Users from CSV
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Read CSV file
      read_csv:
        path: gegevens.csv
      register: csv_content

    - name: Debug CSV Data
      debug:
        var: csv_content

    - name: Use CSV Data as Variables
      set_fact:
        users_data: "{{ csv_content.list }}"

    - name: Create AD Users
      win_domain_user:
        name: "{{ item.gebruikersnaam }}"
        password: "Welkom123456"  # Set a secure password
        state: present
        given_name: "{{ item.voornaam }}"
        surname: "{{ item.achternaam }}"
        street_address: "{{ item.adres }}"
        postal_code: "{{ item.postcode }}"
        city: "{{ item.plaatsnaam }}"
        ou: "OU=Users,DC=example,DC=com"  # Adjust the OU based on your AD structure
      with_items: "{{ users_data }}"