---
# tasks file for ADDS

- name: Install AD DS role
  win_feature:
    name: AD-Domain-Services
    state: present

- name: Promote server to domain controller
  win_domain_controller:
    domain_name: "{{ domainname }}" 
    domain_user: "{{ domainuser }}" 
    domain_pass: "{{ domainpass }}" 
    state: domain
    install_dns: yes
    restart: yes



#- name: Promote server to domain controller
#  win_domain_controller:
#    domain_name: "{{ domainname }}" 
#    domain_user: "{{ domainuser }}" 
#    domain_pass: "{{ domainpass }}" 
#    state: domain
#    safe_mode_pass: SafeModePassword
#    restart: yes

#- name: Configure DNS settings
#  win_dns_client:
#    adapters:
#      - name: "*"
#        ipv4_addresses:
#          - 127.0.0.1