---
- name: Install AD DS role
  win_feature:
    name: AD-Domain-Services
    state: present
    restart: yes
    include_sub_features: yes
    include_management_tools: yes
    
- name: Install Windows Deployment Services
  win_feature:
    name: WDS
    state: present
    restart: yes
    include_sub_features: yes
    include_management_tools: yes

- name: Promote server to domain controller
  win_domain:
    dns_domain_name: "{{ domainname }}" 
    domain_admin_user: "{{ domainuser }}"
    domain_admin_password: "{{ domainpass }}" 
    safe_mode_password: "{{ domainpass }}" 
    state: "domain_controller"
    reboot: true
