---
- name: Install AD DS role
  win_feature:
    name: AD-Domain-Services
    state: present

- name: Install Windows Deployment Services
  win_feature:
    name: Deployment-Services
    state: present

- name: Promote server to domain controller
  win_domain:
    dns_domain_name: "{{ domainname }}" 
    domain_admin_user: "{{ domainuser }}"
    domain_admin_password: "{{ domainpass }}" 
    safe_mode_password: "{{ domainpass }}" 
    state: "domain_controller"
    reboot: true
